# require_relative "../lib/shoe.rb"
# require_relative "../lib/store.rb"

Shoe.destroy_all
Store.destroy_all
Stock.destroy_all

kith = Store.create(name:"Kith",location:"Brooklyn",hours:"11am-7pm",specialty:"Off-White")
extra_butter = Store.create(name:"Extra Butter",location:"Manhattan",hours:"10am-8pm",specialty:"Yeezy")
jimmy_jazz = Store.create(name:"Jimmy Jazz",location:"Queens",hours:"11am-7pm",specialty:"Converse")
sneaker_bar = Store.create(name:"Sneaker Bar",location:"Bronx",hours:"11am-7pm",specialty:"Jordan")
champs = Store.create(name:"Champs",location:"Staten Island",hours:"9am-9pm",specialty:"Ultraboost")
nike_lab = Store.create(name:"Nike Lab",location:"Manhattan",hours:"11am-7pm",specialty:"Air Max")

raptors_10 = Shoe.create(size:10,color:"Black/Purple/Red",brand:"Nike",item_id:"AQ3816-065",model:"Air Jordan 4 Raptors",style:"Basketball",msrp:200)
raptors_13 = Shoe.create(size:13,color:"Black/Purple/Red",brand:"Nike",item_id:"AQ3816-065",model:"Air Jordan 4 Raptors",style:"Basketball",msrp:200)
raptors_11 = Shoe.create(size:11,color:"Black/Purple/Red",brand:"Nike",item_id:"AQ3816-065",model:"Air Jordan 4 Raptors",style:"Basketball",msrp:200)
sesame_10 = Shoe.create(size:10,color:"Sesame/Gum",brand:"Adidas",item_id:"F99710",model:"Yeezy Boost 350 V2 Sesame",style:"Lifestyle",msrp:220)
sesame_9 = Shoe.create(size:9,color:"Sesame/Gum",brand:"Adidas",item_id:"F99710",model:"Yeezy Boost 350 V2 Sesame",style:"Lifestyle",msrp:220)
sesame_8 = Shoe.create(size:8,color:"Sesame/Gum",brand:"Adidas",item_id:"F99710",model:"Yeezy Boost 350 V2 Sesame",style:"Lifestyle",msrp:220)
sesame_11 = Shoe.create(size:11,color:"Sesame/Gum",brand:"Adidas",item_id:"F99710",model:"Yeezy Boost 350 V2 Sesame",style:"Lifestyle",msrp:220)
cdg_7 = Shoe.create(size:7,color:"Black/White/Red",brand:"Converse",item_id:"1127818",model:"Comme des Garcons x Converse Chuck Taylor",style:"Lifestyle",msrp:135)
cdg_9 = Shoe.create(size:9,color:"Black/White/Red",brand:"Converse",item_id:"1127818",model:"Comme des Garcons x Converse Chuck Taylor",style:"Lifestyle",msrp:135)
cdg_10 = Shoe.create(size:10,color:"Black/White/Red",brand:"Converse",item_id:"1127818",model:"Comme des Garcons x Converse Chuck Taylor",style:"Lifestyle",msrp:135)
cdg_12 = Shoe.create(size:12,color:"Black/White/Red",brand:"Converse",item_id:"1127818",model:"Comme des Garcons x Converse Chuck Taylor",style:"Lifestyle",msrp:135)
presto_9 = Shoe.create(size:9,color:"Black/White/Cone",brand:"Nike",item_id:"AA3830-002",model:"Air Presto Off-White",style:"Running",msrp:160)
presto_7 = Shoe.create(size:7,color:"Black/White/Cone",brand:"Nike",item_id:"AA3830-002",model:"Air Presto Off-White",style:"Running",msrp:160)
presto_8 = Shoe.create(size:8,color:"Black/White/Cone",brand:"Nike",item_id:"AA3830-002",model:"Air Presto Off-White",style:"Running",msrp:160)
presto_10 = Shoe.create(size:10,color:"Black/White/Cone",brand:"Nike",item_id:"AA3830-002",model:"Air Presto Off-White",style:"Running",msrp:160)
presto_11 = Shoe.create(size:11,color:"Black/White/Cone",brand:"Nike",item_id:"AA3830-002",model:"Air Presto Off-White",style:"Running",msrp:160)
anniversary_8 = Shoe.create(size:8,color:"White/Red/Gray/Black",brand:"Nike",item_id:"908375-103",model:"Air Max 1 Anniversary",style:"Lifestyle",msrp:140)
anniversary_10 = Shoe.create(size:10,color:"White/Red/Gray/Black",brand:"Nike",item_id:"908375-103",model:"Air Max 1 Anniversary",style:"Lifestyle",msrp:140)
anniversary_12 = Shoe.create(size:12,color:"White/Red/Gray/Black",brand:"Nike",item_id:"908375-103",model:"Air Max 1 Anniversary",style:"Lifestyle",msrp:140)
anniversary_13 = Shoe.create(size:13,color:"White/Red/Gray/Black",brand:"Nike",item_id:"908375-103",model:"Air Max 1 Anniversary",style:"Lifestyle",msrp:140)
ultraboost_9 = Shoe.create(size:9,color:"Black",brand:"Adidas",item_id:"BB6171",model:"Ultraboost 4.0",style:"Running",msrp:200)
ultraboost_8 = Shoe.create(size:8,color:"Black",brand:"Adidas",item_id:"BB6171",model:"Ultraboost 4.0",style:"Running",msrp:200)
ultraboost_11 = Shoe.create(size:11,color:"Black",brand:"Adidas",item_id:"BB6171",model:"Ultraboost 4.0",style:"Running",msrp:200)
supermoon_7 = Shoe.create(size:7,color:"Supermoon Yellow",brand:"Adidas",item_id:"DB2966",model:"Yeezy 500 Supermoon Yellow",style:"Lifestyle",msrp:200)
supermoon_8 = Shoe.create(size:8,color:"Supermoon Yellow",brand:"Adidas",item_id:"DB2966",model:"Yeezy 500 Supermoon Yellow",style:"Lifestyle",msrp:200)
supermoon_9 = Shoe.create(size:9,color:"Supermoon Yellow",brand:"Adidas",item_id:"DB2966",model:"Yeezy 500 Supermoon Yellow",style:"Lifestyle",msrp:200)
supermoon_10 = Shoe.create(size:10,color:"Supermoon Yellow",brand:"Adidas",item_id:"DB2966",model:"Yeezy 500 Supermoon Yellow",style:"Lifestyle",msrp:200)
butter_12 = Shoe.create(size:12,color:"Butter",brand:"Adidas",item_id:"F36980",model:"Yeezy Boost 350 V2 Butter",style:"Lifestyle",msrp:220)
butter_13 = Shoe.create(size:13,color:"Butter",brand:"Adidas",item_id:"F36980",model:"Yeezy Boost 350 V2 Butter",style:"Lifestyle",msrp:220)
top_3_rebel_10 = Shoe.create(size:10,color:"Black/White/Red/Blue",brand:"Nike",item_id:"AT4151-001",model:"Air Jordan Rebel XX OG Top 3",style:"Basketball",msrp:145)
blush_7 = Shoe.create(size:7,color:"Blush",brand:"Adidas",item_id:"DB2908",model:"Yeezy 500 Blush",style:"Lifestyle",msrp:200)
blush_10 = Shoe.create(size:10,color:"Blush",brand:"Adidas",item_id:"DB2908",model:"Yeezy 500 Blush",style:"Lifestyle",msrp:200)
blush_12 = Shoe.create(size:12,color:"Blush",brand:"Adidas",item_id:"DB2908",model:"Yeezy 500 Blush",style:"Lifestyle",msrp:200)
tinker_13 = Shoe.create(size:13,color:"Black/White/Red",brand:"Nike",item_id:"AQ3835-160",model:"Air Jordan 3 Tinker",style:"Basketball",msrp:200)
last_shot_10 = Shoe.create(size:10,color:"Black/Red/Yellow",brand:"Nike",item_id:"487471-003",model:"Air Jordan 14 Last Shot",style:"Basketball",msrp:190)
last_shot_11 = Shoe.create(size:11,color:"Black/Red/Yellow",brand:"Nike",item_id:"487471-003",model:"Air Jordan 14 Last Shot",style:"Basketball",msrp:190)
chicago_rebel_9 = Shoe.create(size:9,color:"Black/White/Red",brand:"Nike",item_id:"AT4151-100",model:"Air Jordan Rebel XX OG Chicago",style:"Basketball",msrp:145)
homage_9 = Shoe.create(size:9,color:"Black/White/Red",brand:"Nike",item_id:"861428-061",model:"Air Jordan 1 Retro High OG Homage To Home",style:"Basketball",msrp:160)
clay_green_13 = Shoe.create(size:13,color:"Black/White/Clay Green",brand:"Nike",item_id:"555088-135",model:"Air Jordan 1 Retro High OG Best Hand In The Game Clay Green",style:"Basketball",msrp:160)
katrina_11 = Shoe.create(size:11,color:"Black/White/Red",brand:"Nike",item_id:"136064-116",model:"Air Jordan 3 Katrina",style:"Basketball",msrp:190)
wave_runner_8 = Shoe.create(size:8,color:"Grey/White/Black/Teal/Orange",brand:"Adidas",item_id:"B75571",model:"Yeezy Boost 700 Wave Runner",style:"Lifestyle",msrp:300)
wave_runner_9 = Shoe.create(size:9,color:"Grey/White/Black/Teal/Orange",brand:"Adidas",item_id:"B75571",model:"Yeezy Boost 700 Wave Runner",style:"Lifestyle",msrp:300)
ovo_12 = Shoe.create(size:12,color:"White/Gold/Red",brand:"Nike",item_id:"AA1239-135",model:"Air Jordan 8 Retro OVO",style:"Basketball",msrp:250)
bred_toe_11 = Shoe.create(size:11,color:"Black/White/Red",brand:"Nike",item_id:"555088-610",model:"Air Jordan 1 Retro High OG Bred Toe",style:"Basketball",msrp:160)
bc3_12 = Shoe.create(size:12,color:"Black/White/Red/Grey",brand:"Nike",item_id:"854262-001",model:"Air Jordan 3 Black Cement",style:"Basketball",msrp:200)
bc3_13 = Shoe.create(size:13,color:"Black/White/Red/Grey",brand:"Nike",item_id:"854262-001",model:"Air Jordan 3 Black Cement",style:"Basketball",msrp:200)
beluga2_10 = Shoe.create(size:10,color:"Grey/Orange",brand:"Adidas",item_id:"AH2203",model:"Yeezy Boost 350 V2 Beluga 2.0",style:"Lifestyle",msrp:220)
blue_tint_7 = Shoe.create(size:7,color:"Blue Tint/Grey/Red",brand:"Adidas",item_id:"B37571",model:"Yeezy Boost 350 V2 Blue Tint",style:"Lifestyle",msrp:220)
blue_tint_8 = Shoe.create(size:8,color:"Blue Tint/Grey/Red",brand:"Adidas",item_id:"B37571",model:"Yeezy Boost 350 V2 Blue Tint",style:"Lifestyle",msrp:220)
blue_tint_9 = Shoe.create(size:9,color:"Blue Tint/Grey/Red",brand:"Adidas",item_id:"B37571",model:"Yeezy Boost 350 V2 Blue Tint",style:"Lifestyle",msrp:220)
powerphase_12 = Shoe.create(size:12,color:"Grey/Gold/Red/Green",brand:"Adidas",item_id:"CG6422",model:"Yeezy Powerphase Calabasas",style:"Lifestyle",msrp:120)
powerphase_13 = Shoe.create(size:13,color:"Grey/Gold/Red/Green",brand:"Adidas",item_id:"CG6422",model:"Yeezy Powerphase Calabasas",style:"Lifestyle",msrp:120)
zebra_10 = Shoe.create(size:10,color:"White/Black/Red",brand:"Adidas",item_id:"CP9654",model:"Yeezy Boost 350 V2 Zebra",style:"Lifestyle",msrp:220)
zebra_11 = Shoe.create(size:11,color:"White/Black/Red",brand:"Adidas",item_id:"CP9654",model:"Yeezy Boost 350 V2 Zebra",style:"Lifestyle",msrp:220)
vapormax_12 = Shoe.create(size:12,color:"Black/White/Cone",brand:"Nike",item_id:"AA3831-002",model:"Air VaporMax Off-White",style:"Running",msrp:250)
blazer_10 = Shoe.create(size:10,color:"Black/White/Cone",brand:"Nike",item_id:"AA3832-100",model:"Blazer Mid Off-White",style:"Lifestyle",msrp:130)
ow_chuck_taylor_7 = Shoe.create(size:7,color:"Black/Ice Blue",brand:"Converse",item_id:"162204C-102",model:"Converse Chuck Taylor Off-White",style:"Lifestyle",msrp:130)
ow_chuck_taylor_8 = Shoe.create(size:8,color:"Black/Ice Blue",brand:"Converse",item_id:"162204C-102",model:"Converse Chuck Taylor Off-White",style:"Lifestyle",msrp:130)
ow_chuck_taylor_9 = Shoe.create(size:9,color:"Black/Ice Blue",brand:"Converse",item_id:"162204C-102",model:"Converse Chuck Taylor Off-White",style:"Lifestyle",msrp:130)
ow_chuck_taylor_10 = Shoe.create(size:10,color:"Black/Ice Blue",brand:"Converse",item_id:"162204C-102",model:"Converse Chuck Taylor Off-White",style:"Lifestyle",msrp:130)
coke_converse_7 = Shoe.create(size:7,color:"Red/White",brand:"Converse",item_id:"CN162989C",model:"Converse Chuck Taylor Kith x Coca Cola",style:"Lifestyle",msrp:150)
coke_converse_8 = Shoe.create(size:8,color:"Red/White",brand:"Converse",item_id:"CN162989C",model:"Converse Chuck Taylor Kith x Coca Cola",style:"Lifestyle",msrp:150)
coke_converse_9 = Shoe.create(size:9,color:"Red/White",brand:"Converse",item_id:"CN162989C",model:"Converse Chuck Taylor Kith x Coca Cola",style:"Lifestyle",msrp:150)
ow_jordan_13 = Shoe.create(size:13,color:"Black/White/Red",brand:"Nike",item_id:"AA3834-101",model:"Jordan 1 Retro High Off-White Chicago",style:"Basketball",msrp:190)


stock1 = Stock.create(store_id:1,shoe_id:1,quantity:5,price:170)
stock2 = Stock.create(store_id:3,shoe_id:4,quantity:3,price:120)
stock3 = Stock.create(store_id:3,shoe_id:1,quantity:2,price:175)
